services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./api:/app/api
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 20s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: streamlit run app.py --server.enableCORS true
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    depends_on:
      - api
    env_file:
      - .env

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: xtremdb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  tests:
    build:
      context: .
      dockerfile: tests/Dockerfile
    environment:
      DATABASE_URL: postgresql://user:pass@db:5432/xtremdb
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_healthy
    entrypoint: ["sh", "-c", "python /app/wait_for_api.py http://api:8000/health 60 && pytest -v --maxfail=1 --disable-warnings tests"]

volumes:
  postgres_data:
