version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - xtrem_net

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - api
    networks:
      - xtrem_net

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: xtremdb
    ports:
      - "5433:5432"
    networks:
      - xtrem_net

  tests:
    build:
      context: .
      dockerfile: tests/Dockerfile.tests
    depends_on:
      - db
      - api
    environment:
      DATABASE_URL: postgresql://user:pass@db:5432/xtremdb
      PYTHONPATH: /app
    volumes:
      - .:/app
    command: >
      sh -c "sleep 5 && pytest tests"
    networks:
      - xtrem_net

volumes:
  postgres_data:

networks:
  xtrem_net:
    driver: bridge
