FROM python:3.12-slim

WORKDIR /tests


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Commande par défaut : lancer les tests
CMD ["pytest", "--maxfail=1", "--disable-warnings", "-v"]
